### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by rxerium** [Nutlope/restorePhotos#31]
Hi there,

Is it possible to change the port to something else? Preferably opening it up to allow users to easily modify the port to their choosing.

Kind regards,

Rishi

**Comment by hakrishi** [comment]
The port changes to 3001 when running `npm run dev` but I am unable to access the web page with the following error:
```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:644:5)
    at parseUrl (/root/restorePhotos/node_modules/next-auth/utils/parse-url.js:17:16)
    at Object.<anonymous> (/root/restorePhotos/node_modules/next-auth/react/index.js:72:34)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at next-auth/react (/root/restorePhotos/.next/server/pages/_app.js:43:18)
    at __webpack_require__ (/root/restorePhotos/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/_app.tsx:9:73)
    at __webpack_require__.a (/root/restorePhotos/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/_app.tsx:1:21)
    at ./pages/_app.tsx (/root/restorePhotos/.next/server/pages/_app.js:22:1)
    at __webpack_require__ (/root/restorePhotos/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/root/restorePhotos/.next/server/pages/_app.js:75:39)
    at /root/restorePhotos/.next/server/pages/_app.js:76:28
    at Object.<anonymous> (/root/restorePhotos/.next/server/pages/_app.js:79:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/root/restorePhotos/node_modules/next/dist/server/require.js:88:12)
    at /root/restorePhotos/node_modules/next/dist/server/load-components.js:45:54
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Object.loadComponents (/root/restorePhotos/node_modules/next/dist/server/load-components.js:43:33)
    at async DevServer.findPageComponents (/root/restorePhotos/node_modules/next/dist/server/next-server.js:563:36)
    at async DevServer.findPageComponents (/root/restorePhotos/node_modules/next/dist/server/dev/next-dev-server.js:1041:20)
    at async DevServer.renderPageComponent (/root/restorePhotos/node_modules/next/dist/server/base-server.js:951:24)
    at async DevServer.renderToResponse (/root/restorePhotos/node_modules/next/dist/server/base-server.js:980:32)
    at async DevServer.pipe (/root/restorePhotos/node_modules/next/dist/server/base-server.js:407:25)
    at async Object.fn (/root/restorePhotos/node_modules/next/dist/server/next-server.js:759:21)
    at async Router.execute (/root/restorePhotos/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/root/restorePhotos/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/root/restorePhotos/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (/root/restorePhotos/node_modules/next/dist/server/base-server.js:322:20) {
  input: '',
  code: 'ERR_INVALID_URL',
  page: '/'
}```

**Comment by hakrishi** [comment]
Hi @Nutlope, is this a known bug?

![image](https://user-images.githubusercontent.com/59293085/236562167-69829ba6-3ef8-4324-8c7f-9771d9bd6db8.png)

**Comment by RoskiDeluge** [comment]
Hi. This issue actually has to do with his comment that auth is incomplete. You'll need to set your head to the commit he specified (1c5c8ac4f52a08f68a3091d3b21be8a65aef71f2) and then do "npm run dev". Here's how to do that:

https://coderwall.com/p/xyuoza/git-cloning-specific-commits

**Comment by rxerium** [comment]
Thanks! Closing for now.
